# Generated by Django 5.2.13 on 2026-04-09 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sedes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': 'Área', 'verbose_name_plural': 'Áreas'},
        ),
        migrations.AlterModelOptions(
            name='sede',
            options={'verbose_name': 'Sede', 'verbose_name_plural': 'Sedes'},
        ),
        migrations.RemoveField(
            model_name='area',
            name='codigo_acceso',
        ),
        migrations.RemoveField(
            model_name='sede',
            name='email',
        ),
        migrations.RemoveField(
            model_name='sede',
            name='encargado',
        ),
        migrations.AlterField(
            model_name='area',
            name='piso',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='sede',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sede',
            name='direccion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sede',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
