# Generated by Django 5.2.7 on 2026-04-11 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sedes', '0002_area_nivel_seguridad'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='dispositivo_biometrico',
            field=models.CharField(choices=[('huella', 'Lector de Huella Dactilar'), ('Tarjeta', 'Tarjeta de Acceso'), ('PIN', 'PIN')], default='huella', max_length=20),
        ),
    ]
