# Generated by Django 5.1.1 on 2026-05-31 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sedes', '0003_area_dispositivo_biometrico'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='codigo_unico',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
