# Generated by Django 5.1.1 on 2026-05-31 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sedes', '0004_sede_codigo_unico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='sede',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='sede',
            name='email',
        ),
        migrations.RemoveField(
            model_name='sede',
            name='encargado',
        ),
        migrations.RemoveField(
            model_name='sede',
            name='telefono',
        ),
    ]
