# Generated by Django 5.1.1 on 2026-05-31 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sedes', '0005_remove_area_descripcion_remove_sede_ciudad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='dispositivo_biometrico',
            field=models.CharField(blank=True, choices=[('huella', 'Lector de Huella Dactilar'), ('Tarjeta', 'Tarjeta de Acceso'), ('PIN', 'PIN')], default='huella', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sede',
            name='nivel_seguridad',
            field=models.CharField(blank=True, choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto')], default='bajo', max_length=20, null=True),
        ),
    ]
