# Generated by Django 6.0.4 on 2026-04-09 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispositivos', '0001_initial'),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ACCESO_NO_AUTORIZADO', 'Acceso No Autorizado'), ('DISPOSITIVO_OFFLINE', 'Dispositivo Offline'), ('INTENTO_FALLIDO', 'Intento Fallido'), ('PUERTA_ABIERTA', 'Puerta Abierta'), ('MANTENIMIENTO', 'Mantenimiento Requerido')], max_length=30)),
                ('nivel', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], max_length=10)),
                ('mensaje', models.TextField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('leida', models.BooleanField(default=False)),
                ('resuelta', models.BooleanField(default=False)),
                ('dispositivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dispositivos.dispositivo')),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personal.persona')),
            ],
        ),
    ]
