# Generated by Django 5.2.13 on 2026-04-09 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alerta',
            options={'verbose_name': 'Alerta', 'verbose_name_plural': 'Alertas'},
        ),
        migrations.AlterField(
            model_name='alerta',
            name='mensaje',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='nivel',
            field=models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=10),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='tipo',
            field=models.CharField(choices=[('ACCESO_NO_AUTORIZADO', 'Acceso No Autorizado'), ('DISPOSITIVO_OFFLINE', 'Dispositivo Offline'), ('INTENTO_FALLIDO', 'Intento Fallido'), ('PUERTA_ABIERTA', 'Puerta Abierta'), ('MANTENIMIENTO', 'Mantenimiento Requerido')], default='MANTENIMIENTO', max_length=30),
        ),
    ]
