# Generated by Django 5.1.1 on 2026-05-30 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudregistro',
            name='dni',
            field=models.CharField(default=0, max_length=20, verbose_name='DNI'),
            preserve_default=False,
        ),
    ]
