# Generated by Django 5.1.1 on 2026-06-01 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_solicitudregistro_dni'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificar_alertas', models.BooleanField(default=True)),
                ('notificar_dispositivos', models.BooleanField(default=True)),
                ('notificar_personal', models.BooleanField(default=True)),
                ('notificar_sedes', models.BooleanField(default=True)),
                ('notificar_reportes', models.BooleanField(default=True)),
                ('notificar_backup', models.BooleanField(default=True)),
                ('notificar_configuracion', models.BooleanField(default=True)),
                ('notificar_seguridad', models.BooleanField(default=True)),
                ('prioridad_minima', models.CharField(choices=[('critica', 'Crítica'), ('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja'), ('informativa', 'Informativa')], default='baja', max_length=20)),
                ('email_notificaciones', models.BooleanField(default=False)),
                ('email_destino', models.EmailField(blank=True, max_length=254, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(choices=[('ALERTA', 'Alerta del Sistema'), ('DISPOSITIVO', 'Dispositivo'), ('PERSONAL', 'Personal'), ('SEDE', 'Sede/Área'), ('REPORTE', 'Reporte'), ('BACKUP', 'Backup'), ('CONFIGURACION', 'Configuración'), ('SEGURIDAD', 'Seguridad'), ('MANTENIMIENTO', 'Mantenimiento')], max_length=20)),
                ('prioridad', models.CharField(choices=[('critica', 'Crítica'), ('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja'), ('informativa', 'Informativa')], default='informativa', max_length=20)),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('datos_extra', models.JSONField(blank=True, default=dict)),
                ('usuario_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
