# Generated by Django 5.2.7 on 2026-04-11 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispositivos', '0001_initial'),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('ACCESO_DIARIO', 'Acceso Diario'), ('ACCESO_SEMANAL', 'Acceso Semanal'), ('ACCESO_MENSUAL', 'Acceso Mensual'), ('DISPOSITIVO', 'Estado de Dispositivos'), ('INCIDENTES', 'Incidentes de Seguridad'), ('CUMPLIMIENTO', 'Cumplimiento'), ('PERSONALIZADO', 'Personalizado')], max_length=20)),
                ('frecuencia', models.CharField(choices=[('DIARIA', 'Diaria'), ('SEMANAL', 'Semanal'), ('MENSUAL', 'Mensual')], max_length=20)),
                ('activa', models.BooleanField(default=True)),
                ('email_destino', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Configuraciones de Reportes',
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('ACCESO_DIARIO', 'Acceso Diario'), ('ACCESO_SEMANAL', 'Acceso Semanal'), ('ACCESO_MENSUAL', 'Acceso Mensual'), ('DISPOSITIVO', 'Estado de Dispositivos'), ('INCIDENTES', 'Incidentes de Seguridad'), ('CUMPLIMIENTO', 'Cumplimiento'), ('PERSONALIZADO', 'Personalizado')], max_length=20)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('COMPLETADO', 'Completado'), ('ERROR', 'Error')], default='PENDIENTE', max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_generacion', models.DateTimeField(blank=True, null=True)),
                ('total_registros', models.IntegerField(default=0)),
                ('accesos_exitosos', models.IntegerField(default=0)),
                ('accesos_fallidos', models.IntegerField(default=0)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='reportes/')),
                ('dispositivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dispositivos.dispositivo')),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal.persona')),
            ],
            options={
                'verbose_name_plural': 'Reportes',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
