# Generated by Django 5.2.13 on 2026-04-08 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispositivos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula'), ('CE', 'Cédula Extranjería'), ('PAS', 'Pasaporte')], max_length=3)),
                ('numero_documento', models.CharField(max_length=20, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('tipo_persona', models.CharField(choices=[('RES', 'Residente'), ('VIS', 'Visitante'), ('EMP', 'Empleado'), ('ADM', 'Administrador')], max_length=3)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Personas',
            },
        ),
        migrations.CreateModel(
            name='RegistroAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_acceso', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('DENEGADO', 'Denegado')], max_length=10)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('temperatura', models.FloatField(blank=True, null=True)),
                ('motivo_denegado', models.CharField(blank=True, max_length=200)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispositivos.dispositivo')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos', to='personal.persona')),
            ],
        ),
    ]
