# Generated by Django 5.1.1 on 2026-05-14 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='metodo_adicional',
            field=models.JSONField(blank=True, null=True, verbose_name='Método de Autenticación Adicional'),
        ),
    ]
