# Generated by Django 5.2.13 on 2026-04-09 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'verbose_name': 'Persona', 'verbose_name_plural': 'Personas'},
        ),
        migrations.AlterField(
            model_name='persona',
            name='apellidos',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='persona',
            name='direccion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='persona',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombres',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='persona',
            name='numero_documento',
            field=models.CharField(default='00000000', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='telefono',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='persona',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula'), ('CE', 'Cédula Extranjería'), ('PAS', 'Pasaporte')], default='CC', max_length=3),
        ),
        migrations.AlterField(
            model_name='persona',
            name='tipo_persona',
            field=models.CharField(choices=[('RES', 'Residente'), ('VIS', 'Visitante'), ('EMP', 'Empleado'), ('ADM', 'Administrador')], default='EMP', max_length=3),
        ),
        migrations.DeleteModel(
            name='RegistroAcceso',
        ),
    ]
