# Generated by Django 5.2.13 on 2026-04-09 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispositivos', '0002_alter_dispositivo_options_and_more'),
        ('personal', '0002_alter_persona_options_alter_persona_apellidos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_acceso', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('DENEGADO', 'Denegado')], default='ENTRADA', max_length=10)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('temperatura', models.FloatField(blank=True, null=True)),
                ('motivo_denegado', models.CharField(blank=True, default='', max_length=200)),
                ('dispositivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dispositivos.dispositivo')),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accesos', to='personal.persona')),
            ],
            options={
                'verbose_name': 'Registro de Acceso',
                'verbose_name_plural': 'Registros de Acceso',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
