# Generated by Django 6.0.4 on 2026-04-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Dispositivo')),
                ('numero_serie', models.CharField(max_length=50, unique=True, verbose_name='Número de Serie')),
                ('tipo_sede', models.CharField(choices=[('sede', 'Sede Principal'), ('oficina', 'Oficina'), ('area', 'Área Específica'), ('almacen', 'Almacén')], max_length=20, verbose_name='Tipo de Sede')),
                ('area', models.CharField(max_length=100, verbose_name='Área/Ubicación')),
                ('direccion', models.CharField(blank=True, max_length=200, verbose_name='Dirección Física')),
                ('direccion_ip', models.GenericIPAddressField(verbose_name='Dirección IP')),
                ('zona_horaria', models.CharField(choices=[('America/Mexico_City', 'CDMX (UTC-6)'), ('America/Bogota', 'Bogotá (UTC-5)'), ('America/Buenos_Aires', 'Buenos Aires (UTC-3)'), ('America/Lima', 'Lima (UTC-5)'), ('America/Santiago', 'Santiago (UTC-4)')], max_length=50, verbose_name='Zona Horaria')),
                ('intervalo_solicitud', models.IntegerField(default=5, verbose_name='Intervalo de Solicitud (minutos)')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('pausado', 'Pausado'), ('error', 'Error'), ('sin_conexion', 'Sin Conexión'), ('apagado', 'Apagado')], default='activo', max_length=20, verbose_name='Estado')),
                ('tipo_dispositivo', models.CharField(choices=[('huella', 'Lector de Huella'), ('tarjeta', 'Lector de Tarjeta'), ('facial', 'Reconocimiento Facial'), ('iris', 'Escáner de Iris'), ('multi', 'Multibiométrico')], default='huella', max_length=20, verbose_name='Tipo de Dispositivo')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('ultima_conexion', models.DateTimeField(auto_now=True, verbose_name='Última Conexión')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('api_key', models.CharField(blank=True, max_length=100, unique=True, verbose_name='API Key')),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivos',
                'ordering': ['nombre'],
            },
        ),
    ]
