# Generated by Django 5.2.13 on 2026-04-08 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sedes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('HUELLA', 'Lector de Huellas'), ('FACIAL', 'Reconocimiento Facial'), ('HIBRIDO', 'Híbrido (Huella+Facial)'), ('TARJETA', 'Lector de Tarjetas')], max_length=20)),
                ('ip_address', models.GenericIPAddressField()),
                ('puerto', models.IntegerField(default=80)),
                ('ubicacion', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('MANTENIMIENTO', 'Mantenimiento'), ('OFFLINE', 'Offline')], default='ACTIVO', max_length=20)),
                ('ultimo_mantenimiento', models.DateTimeField(blank=True, null=True)),
                ('ultimo_online', models.DateTimeField(auto_now=True)),
                ('api_key', models.CharField(blank=True, max_length=100, unique=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sedes.area')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to='sedes.sede')),
            ],
        ),
    ]
