# Generated by Django 5.1.1 on 2026-05-12 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='modelos_cargados',
            field=models.TextField(blank=True, verbose_name='Modelos Cargados (JSON)'),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='ultima_carga_modelos',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última Carga de Modelos'),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='tipo_dispositivo',
            field=models.CharField(choices=[('huella', 'Lector de Huella Digital'), ('pin', 'Lector de PIN (Código Numérico)'), ('huella_pin', 'Huella + PIN (Combinado)'), ('facial', 'Reconocimiento Facial')], default='huella_pin', max_length=20, verbose_name='Tipo de Dispositivo'),
        ),
    ]
