# Generated by Django 5.2.13 on 2026-04-09 06:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dispositivo',
            options={'verbose_name': 'Dispositivo', 'verbose_name_plural': 'Dispositivos'},
        ),
        migrations.RenameField(
            model_name='dispositivo',
            old_name='ultimo_online',
            new_name='ultima_conexion',
        ),
        migrations.RemoveField(
            model_name='dispositivo',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='dispositivo',
            name='puerto',
        ),
        migrations.RemoveField(
            model_name='dispositivo',
            name='sede',
        ),
        migrations.RemoveField(
            model_name='dispositivo',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='dispositivo',
            name='ubicacion',
        ),
        migrations.RemoveField(
            model_name='dispositivo',
            name='ultimo_mantenimiento',
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='direccion',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='direccion_ip',
            field=models.GenericIPAddressField(default='192.168.1.1'),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='intervalo_solicitud',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='observaciones',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='tipo_dispositivo',
            field=models.CharField(choices=[('huella', 'Lector de Huella'), ('tarjeta', 'Lector de Tarjeta'), ('facial', 'Reconocimiento Facial'), ('iris', 'Escáner de Iris'), ('multi', 'Multibiométrico')], default='huella', max_length=20),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='tipo_sede',
            field=models.CharField(default='sede', max_length=20),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='zona_horaria',
            field=models.CharField(default='America/Buenos_Aires', max_length=50),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='api_key',
            field=models.CharField(blank=True, default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='area',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('pausado', 'Pausado'), ('error', 'Error'), ('sin_conexion', 'Sin Conexión'), ('apagado', 'Apagado')], default='activo', max_length=20),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='nombre',
            field=models.CharField(default='Dispositivo', max_length=100),
        ),
    ]
