# Generated by Django 5.1.1 on 2026-05-13 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0002_dispositivo_modelos_cargados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='modelo_dispositivo',
            field=models.CharField(choices=[('reloj_ip65', 'Control de Acceso por Huella – Reloj – IP – IP65'), ('molinete_zk', 'Molinete Biométrico ZK TS2022')], default='reloj_ip65', max_length=50, verbose_name='Modelo del Dispositivo'),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='tipo_dispositivo',
            field=models.CharField(choices=[('pin', 'Solo PIN'), ('huella', 'Solo Huella Digital'), ('tarjeta', 'Solo Tarjeta RFID'), ('pin_huella', 'PIN + Huella'), ('pin_tarjeta', 'PIN + Tarjeta'), ('huella_tarjeta', 'Huella + Tarjeta')], default='pin_huella', max_length=20, verbose_name='Tipo de Dispositivo'),
        ),
    ]
