# Generated by Django 5.1.1 on 2026-05-11 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='fecha_resolucion',
            field=models.DateTimeField(blank=True, help_text='Fecha cuando se resolvió el ticket', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='remitente_email',
            field=models.EmailField(blank=True, help_text='Email de la persona que reporta el ticket', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='remitente_nombre',
            field=models.CharField(blank=True, help_text='Nombre de la persona que reporta el ticket', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='solucion',
            field=models.TextField(blank=True, help_text='Solución proporcionada al ticket', null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='estado',
            field=models.CharField(choices=[('abierto', 'Abierto'), ('en_progreso', 'En Progreso'), ('resuelto', 'Resuelto'), ('cerrado', 'Cerrado')], default='abierto', max_length=20),
        ),
    ]
