# Generated by Django 5.1.1 on 2026-05-11 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_fecha_resolucion_ticket_remitente_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='fecha_resolucion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='remitente_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='remitente_nombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='solucion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
